biocypher:
  strict_mode: false
  schema_config_path: ../../example/custom_subset/schema_config.yaml

neo4j:
  database_name: custom_subset
  delimiter: '\t'
  quote_character: "@"
  array_delimiter: "|"
  skip_bad_relationships: true
