biocypher:
  strict_mode: false
  schema_config_path: config/schema_config_reference_kg.yaml

neo4j:
  database_name: test
  delimiter: '\t'
  quote_character: '@'
  array_delimiter: '|'
  skip_bad_relationships: true