biocypher:
  strict_mode: false
  schema_config_path: example/full_graph/schema_config.yaml

neo4j:
  database_name: reference_kg
  delimiter: '\t'
  quote_character: "@"
  array_delimiter: "|"
  skip_bad_relationships: true
